[oobe]
command=/usr/libexec/atl-wsl-oobe
defaultUid=1000
defaultName=ATL-WSL

[shortcut]
enabled=true
icon=/usr/share/atl-wsl/atl-wsl.ico

[windowsterminal]
enabled=true
profileTemplate=/usr/share/atl-wsl/terminal-profile.json
